### ISSUE TITLE
Handle accessors on Node.js Stack Processor

### ISSUE THREAD

**Issue by mmarchini** [Netflix/nflxprofile#8]
For code like this:

```js
class Foo {
   // ...
   get bar() {
   }
}
```

The Node.js Stack Processor is using `get` as the function name instead of `bar`. It should use `get bar` instead. Since there's no separation between the function name and the file name, and since the file path can have spaces, this will be tricky to handle.

**Comment by jasonk000** [comment]
fixed in #18
